export default function Privacy() {
  return (
    <>
      <p className="text-label uppercase text-text-tertiary">Effective 2026-01-01</p>
      <h1 className="mt-2 text-h1 md:text-h1-lg text-text-primary">Privacy policy</h1>

      <Section title="What we collect">
        <p>
          Information you provide (name, mobile, address, prescriptions, family member details)
          and information generated by your use (orders, searches, viewed medicines, device type).
        </p>
      </Section>
      <Section title="Why we collect it">
        <ul>
          <li>To verify your identity and prevent fraud</li>
          <li>To dispense medicines safely and lawfully</li>
          <li>To deliver your orders and process payments</li>
          <li>To send order, prescription, and refill notifications</li>
          <li>To improve product recommendations</li>
        </ul>
      </Section>
      <Section title="How we share data">
        <p>
          With delivery partners (only what is needed to deliver), payment processors (transaction
          data), and licensed pharmacists (prescription images). We never sell your data.
        </p>
      </Section>
      <Section title="Data retention">
        <p>
          Account data: until you delete your account. Prescription images: retained for 2 years
          for Schedule H1 items, as required by the Drugs and Cosmetics Act. Order records:
          retained for 7 years per tax law.
        </p>
      </Section>
      <Section title="Your rights (DPDP Act 2023)">
        <ul>
          <li>Access, correct, and delete your data — Account → Settings</li>
          <li>Withdraw consent for any processing — Account → Notifications</li>
          <li>Export your data in a portable format</li>
          <li>Lodge a grievance with our DPO at privacy@med.example</li>
        </ul>
      </Section>
      <Section title="Cookies and tracking">
        <p>
          We use first-party cookies and `localStorage` for session, cart, and preferences. We do
          not use cross-site tracking cookies. Analytics is privacy-preserving and opt-in via the
          consent banner.
        </p>
      </Section>
      <Section title="Contact">
        <p>
          Data Protection Officer: privacy@med.example. Response within 7 working days, per DPDP
          Section 13(1)(b).
        </p>
      </Section>
    </>
  );
}

function Section({ title, children }) {
  return (
    <section className="mt-6">
      <h2 className="text-h3 text-text-primary">{title}</h2>
      <div className="mt-2 text-body text-text-secondary space-y-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1">
        {children}
      </div>
    </section>
  );
}
